name: The First Action
on: 
  push: 
    branches:    
      - main

jobs:
  the-first-job: 
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: echo first
        run: |
          echo "The First Job, HAHAHA"
  the-Second-job: 
    name: Second Job
    runs-on: ubuntu-latest
    needs: the-first-job
    steps:
      - name: echo second
        run: |
          echo "The Second Job, AO WU~~~"
